#!/usr/bin/env bash
# =============================================================================
#  TMIS — One-Shot VPS Deployment Script (HTTP, no SSL required)
#  Usage:  bash deploy.sh
# =============================================================================
set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${BLUE}${BOLD}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}${BOLD}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}${BOLD}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}${BOLD}[ERROR]${RESET} $*"; exit 1; }
step()    { echo -e "\n${BOLD}━━━  $* ${RESET}"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "
${BOLD}${BLUE}
 ████████╗███╗   ███╗██╗███████╗
    ██╔══╝████╗ ████║██║██╔════╝
    ██║   ██╔████╔██║██║███████╗
    ██║   ██║╚██╔╝██║██║╚════██║
    ██║   ██║ ╚═╝ ██║██║███████║
    ╚═╝   ╚═╝     ╚═╝╚═╝╚══════╝
${RESET}${BOLD}  Rental Units Management System${RESET}
  Deployment Script — HTTP Mode (No SSL)
  Made with ❤️  by Smart Stack
"

# ── Step 1: Check OS ──────────────────────────────────────────────────────────
step "1/8  Checking system requirements"

OS_ID=""
if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS_ID=$ID
fi

if [[ "$OS_ID" != "ubuntu" && "$OS_ID" != "debian" ]]; then
  warn "This script is tested on Ubuntu/Debian. Detected: ${OS_ID:-unknown}"
  warn "Proceeding anyway — you may need to adapt package manager commands."
fi

success "OS: ${PRETTY_NAME:-$OS_ID}"

# ── Step 2: Install Docker ────────────────────────────────────────────────────
step "2/8  Docker & Docker Compose"

install_docker() {
  info "Installing Docker..."
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg lsb-release

  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/${OS_ID}/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg

  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/${OS_ID} \
    $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list

  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable --now docker
  success "Docker installed"
}

if ! command -v docker &>/dev/null; then
  if [ "$(id -u)" != "0" ]; then
    error "Docker not found. Re-run this script as root (sudo bash deploy.sh) to install it automatically."
  fi
  install_docker
else
  DOCKER_VER=$(docker --version | awk '{print $3}' | tr -d ',')
  success "Docker already installed: v${DOCKER_VER}"
fi

if ! docker compose version &>/dev/null; then
  if [ "$(id -u)" = "0" ]; then
    apt-get install -y -qq docker-compose-plugin
  else
    error "Docker Compose plugin not found. Run: sudo apt install docker-compose-plugin"
  fi
fi

COMPOSE_VER=$(docker compose version --short 2>/dev/null || echo "unknown")
success "Docker Compose: v${COMPOSE_VER}"

# ── Step 3: Detect server IP ──────────────────────────────────────────────────
step "3/8  Detecting server address"

DETECTED_IP=$(curl -s --connect-timeout 5 ifconfig.me 2>/dev/null \
  || curl -s --connect-timeout 5 api.ipify.org 2>/dev/null \
  || hostname -I | awk '{print $1}')

if [ -z "$DETECTED_IP" ]; then
  DETECTED_IP="localhost"
fi

echo -e "  Detected public IP: ${BOLD}${DETECTED_IP}${RESET}"
read -rp "  Use this address? Press Enter to confirm or type a different IP/domain: " USER_INPUT
SERVER_IP="${USER_INPUT:-$DETECTED_IP}"
success "Server address set to: ${SERVER_IP}"

# ── Step 4: Configure .env ────────────────────────────────────────────────────
step "4/8  Environment configuration"

generate_secret() {
  node -e "console.log(require('crypto').randomBytes(48).toString('hex'))" 2>/dev/null \
    || openssl rand -hex 48 2>/dev/null \
    || cat /dev/urandom | tr -dc 'a-f0-9' | head -c 96
}

if [ -f "$ENV_FILE" ]; then
  warn ".env already exists — keeping existing secrets."
  warn "Delete .env and re-run deploy.sh to regenerate secrets."
  # Load existing values so they are available below
  set -a; source "$ENV_FILE"; set +a
else
  info "Generating secure secrets..."

  ACCESS_SECRET=$(generate_secret)
  REFRESH_SECRET=$(generate_secret)
  DB_PASS=$(generate_secret | head -c 32)

  cat > "$ENV_FILE" << ENVEOF
# TMIS Environment — generated by deploy.sh on $(date -u +"%Y-%m-%d %T UTC")
# Keep this file secret — never commit it to version control.

SERVER_IP=${SERVER_IP}

DB_PASSWORD=${DB_PASS}

JWT_ACCESS_SECRET=${ACCESS_SECRET}
JWT_REFRESH_SECRET=${REFRESH_SECRET}
ENVEOF

  success ".env created with auto-generated secrets"
fi

# Reload env
set -a; source "$ENV_FILE"; set +a

# ── Step 5: Pull latest code ──────────────────────────────────────────────────
step "5/8  Codebase"

if git -C "$SCRIPT_DIR" rev-parse --git-dir &>/dev/null; then
  CURRENT_BRANCH=$(git -C "$SCRIPT_DIR" rev-parse --abbrev-ref HEAD)
  info "Git repo detected on branch: ${CURRENT_BRANCH}"
  read -rp "  Pull latest code from origin? [Y/n]: " DO_PULL
  if [[ "${DO_PULL:-Y}" =~ ^[Yy]$ ]]; then
    git -C "$SCRIPT_DIR" pull origin "$CURRENT_BRANCH"
    success "Code updated"
  else
    info "Skipping pull — using current local code"
  fi
else
  info "Not a git repository — using files in current directory"
fi

# ── Step 6: Build & start containers ─────────────────────────────────────────
step "6/8  Building and starting containers"

cd "$SCRIPT_DIR"

info "Building Docker images (this may take a few minutes on first run)..."
docker compose build --no-cache

info "Starting all services..."
docker compose up -d

# Wait for backend health
info "Waiting for backend to become healthy..."
MAX_WAIT=90
WAITED=0
until curl -sf "http://localhost:4000/api/health" &>/dev/null; do
  if [ $WAITED -ge $MAX_WAIT ]; then
    error "Backend did not start in ${MAX_WAIT}s. Run: docker compose logs backend"
  fi
  printf "."
  sleep 3
  WAITED=$((WAITED + 3))
done
echo ""
success "Backend is healthy"

# ── Step 7: Seed database (first deploy only) ─────────────────────────────────
step "7/8  Database seeding"

SEED_FLAG="$SCRIPT_DIR/.tmis_seeded"

if [ ! -f "$SEED_FLAG" ]; then
  info "First deployment detected — seeding default admin user..."

  docker compose exec -T backend node -e "
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');
const prisma = new PrismaClient();
bcrypt.hash('Admin@1234', 12).then(hash =>
  prisma.user.upsert({
    where:  { email: 'admin@tmis.local' },
    update: {},
    create: {
      firstName: 'System',
      lastName:  'Admin',
      email:     'admin@tmis.local',
      phone:     '+255700000000',
      password:  hash,
      role:      'ADMIN',
      isActive:  true,
    },
  })
).then(() => {
  console.log('Admin user seeded');
  return prisma.\$disconnect();
}).catch(e => { console.error(e); process.exit(1); });
"

  touch "$SEED_FLAG"
  success "Database seeded"
else
  info "Database already seeded — skipping"
fi

# ── Step 8: Status summary ────────────────────────────────────────────────────
step "8/8  Deployment complete"

echo ""
docker compose ps
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════════════╗"
echo -e "║            TMIS is now running! 🎉                  ║"
echo -e "╚══════════════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "  ${BOLD}Application URL:${RESET}   http://${SERVER_IP}"
echo -e "  ${BOLD}API Health:${RESET}        http://${SERVER_IP}/api/health"
echo ""
echo -e "  ${BOLD}Default Login:${RESET}"
echo -e "    Email    →  admin@tmis.local"
echo -e "    Password →  Admin@1234"
echo ""
echo -e "  ${YELLOW}${BOLD}⚠  Change the default password immediately after first login!${RESET}"
echo ""
echo -e "  ${BOLD}Useful commands:${RESET}"
echo -e "    View logs      →  docker compose logs -f"
echo -e "    Restart        →  docker compose restart"
echo -e "    Stop           →  docker compose down"
echo -e "    Update & redeploy →  bash deploy.sh"
echo ""
echo -e "  Made with ❤️  by Smart Stack"
echo ""
